spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram
    username: pictgram
    password: password
  h2:
    console:
      enabled: true
  security:
     oauth2:
       client:
         registration:
           google:
             client-id: ${google.client.id}
             client-secret: ${google.client.secret}
             
debug: true
  
image:
  local: false